name: Pull Request pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # You can specify the desired version of .NET here

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/Booking

    - name: Build
      run: dotnet build --configuration Release
      working-directory: src/Booking

    - name: Test
      run: dotnet test
      working-directory: src/Booking
